engines:
  rubocop:
    enabled: true
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  fixme:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby:
ratings:
  paths:
  - app/**
  - lib/**
  - "**.rb"
exclude_paths:
exclude_paths:
  - spec/**/*
  - "**/vendor/**/*"
  - "db/migrate/*"
  - "db/schema.rb"
  - "bin/*"
